### ISSUE TITLE
Can't Works with MCPermissions 0.3

### ISSUE THREAD

**Issue by Aliset** [keepcalm/BukkitForge#251]
## That's crash-reports of BukkitForge work with MCPermissions 0.3 

Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: org.yaml.snakeyaml.introspector.PropertyUtils.setSkipMissingProperties(Z)V
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:117)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:486)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:345)
    at ho.c(DedicatedServer.java:64)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.introspector.PropertyUtils.setSkipMissingProperties(Z)V
    at noppes.permissions.PermissionsController.loadPermissions(PermissionsController.java:190)
    at noppes.permissions.MCPermissions.loadPermissions(MCPermissions.java:112)
    at noppes.permissions.MCPermissions.load(MCPermissions.java:54)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:483)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:485)
##     ... 5 more

MCPermissions 0.3 link http://www.minecraftforum.net/topic/1554879-146-mcpermissions-and-mcprotect-03-wip-prevent-new-players-from-griefing-and-protect-regions-on-your-server/

**Comment by shakey2** [comment]
#115 In short they use different versions of yaml thus they can't work together.

**Comment by ghost** [comment]
use PEX for bukkitforge

**Comment by SpoonsJTD** [comment]
Closing all permissions issues except one as dupes.
